steps:
- name: 'gcr.io/cloud-builders/gradle'
  args: ['assemble']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA', '.']
- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - set
  - image
  - deployments/poc-spring-app
  - github-tehcyx-cloud-build-spring-poc=gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=your-first-cluster-1'
images: ['gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA']