steps:
- name: 'gcr.io/cloud-builders/gradle'
  args: ['assemble']
- name: 'gcr.io/cloud-builders/gradle'
  args: ['test']
- name: 'gcr.io/cloud-builders/gradle'
  args: ['check', '--continue']
- name: 'gcr.io/$PROJECT_ID/docker-compose'
  args: ['-f', 'cloud-build/integration-test/docker-compose.yaml', 'up']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA', '.']
images: ['gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA']