steps:
- name: 'java:8'
  env: ['GRADLE_USER_HOME=cache']
  entrypoint: 'bash'
  args: ['-c', './gradlew assemble']
- name: 'java:8'
  env: ['GRADLE_USER_HOME=cache']
  entrypoint: 'bash'
  args: ['-c', './gradlew test']
- name: 'java:8'
  env: ['GRADLE_USER_HOME=cache']
  entrypoint: 'bash'
  args: ['-c', './gradlew check --continue']
  volumes:
    - name: 'test-results'
      path: '/test-results'
- name: 'gcr.io/$PROJECT_ID/docker-compose'
  args: ['-f', 'cloud-build/integration-test/docker-compose.yaml', 'up', '--abort-on-container-exit']
  volumes:
    - name: 'test-results'
      path: '/test-results'
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA', '.']
images: ['gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA']
tags:
  - 'cloud-build'
  - 'spring'
  - 'feature'
  - 'build'
  - 'deploy'